services:
  - type: web
    name: eblg-proxy
    env: node
    region: frankfurt
    plan: free

    # Racine du repo (pas backend !)
    rootDir: .

    # Installer les dépendances dans /backend
    buildCommand: "npm install --prefix backend"

    # Lancer le serveur Express dans /backend
    startCommand: "node backend/server.mjs"

    autoDeploy: true

    envVars:
      NODE_VERSION: 18
