services:
  - type: web
    name: eblg-proxy
    env: node
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: "npm install"
    startCommand: "node server.mjs"
    autoDeploy: true
    envVars:
      NODE_VERSION: 18
